### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by tedstrauss** [CenterForOpenScience/ember-preprints#420]
I am installing this app, and succeeded in starting the ember app, which is serving content via local `curl` calls. Currently stuck at starting up the API server, and the `add-domain.js` script.

My questions are:

1. Is this project a generic preprint server, or is it the network linking together multiple preprint servers. I am trying to setup a generic stand-alone preprint server, that could one day join the network.

2. Does the main OSF app need to be installed first for the preprint server to work? The following section of the installation instructions seem to imply that OSF needs to be installed. I would rather just run a preprint server without any other faetures of the OSF platform.

```
Running / Development
For local development, this is designed to run alongside (and from within) the flask application for osf.io.
Check out this OSF feature branch: https://github.com/CenterForOpenScience/osf.io/tree/feature/ember-preprints
Start your Ember server: ember serve
Copy these lines to your website/settings/local.py file. Uncomment '/preprints/': 'http://localhost:4200', and restart your flask app.
Visit your app at http://localhost:5000/preprints/
```

**Comment by jamescdavis** [comment]
@tedstrauss, this Ember app is the front end for a generic preprint server that can be branded and supports multiple preprint services, but it relies on the OSF as a back-end. To use this as a stand-alone preprint server, you would need to run the main OSF. You could theoretically run this Ember app on top of your own API that exposes the same endpoints as the OSF, but you'd have to implement that yourself. Alternately, the Center for Open Science may be able to offer you a hosted branded preprint service. See https://cos.io/our-products/osf-preprints/ for more details.

**Comment by tedstrauss** [comment]
Got it. Will try to install OSF first, following instructions in the readme here https://github.com/CenterForOpenScience/osf.io/tree/feature/ember-preprints#installation
And then come back to preprints.
Cheers

**Comment by jamescdavis** [comment]
Hope you were able to get it working. Closing this issue, but feel free to re-open if you are still having trouble.
