### ISSUE TITLE
Is there an API to search for preprints only?

### ISSUE THREAD

**Issue by jibe-b** [CenterForOpenScience/ember-preprints#458]
OSF preprint servers could be sources of scientific preprints to [Searx](github.com/asciimoo/searx) users. There already are BASE and coming PubMed, CORE, OpenAIRE.

I found the API for the OSF. Is there a filtering option to just get preprints? Or maybe a separate API?

**Comment by jamescdavis** [comment]
There is a preprints endpoint available [here](https://api.osf.io/v2/preprints/) that is documented [here](https://developer.osf.io/#Preprints_preprints_list).

**Comment by jibe-b** [comment]
Great, thank you @jamescdavis! I am a bit ashamed as it the URL is predictable…

**Comment by jibe-b** [comment]
I will add an engine to Searx to make OSF preprints appear in Searx and update this issue.

**Comment by jamescdavis** [comment]
:+1: Closing this issue, but feel free to re-open if you have more questions about the preprints API.
